language: ruby
rvm:
- 2.2
- 2.1
- 2.0
- 1.9.3
sudo: false
services:
- docker
script:
- >
  wget -O- bit.ly/ansibletest | env
  DOCKER_IMAGES="ubuntu:14.04 ubuntu:16.04"
  ANSIBLE_VERSIONS="1.4.4 1.6.1 1.8.4 2.1.0.0" sh -x
after_failure:
- cat role-tester-ansible-master/.kitchen.yml
- cat role-tester-ansible-master/.kitchen.local.yml
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    on_success: change
    on_failure: change
    rooms:
    - secure: TWdCOYA/5mv5U2A/bMTR+hSSVB8So+LIwlqPjWSfGQfxf1rUf/JpvVk043But7lzXu9heaWfW7krrVR0AeDyUH7vGC3Ar1tXSvRFJmxFJQ1DH/bE43G/fEPWrmpsChkshxFpUCckUlJPAj/51ES+bGeerW0wf3ixS8L877zDYDpZIRXo9wHjTkgG5PpbVaiwdsOffThVGE3B5yxOMAdYObvvxCdfHuhoNVKake1+E9D8ZNJ2VAd+fwKk0Wai5IFfLuw3ZbCu2DHlwLF63krgYyBpX6DBa2SwuBZQs8jUBzL1nacw49X4OJuOEyed9Bq+Ssd5Wihv+yBv2DqKVvCQY300KM6gBLg9js9rrioHJ2kRBAxvfbvVp/Qa903IAhM+Bvr7P3HO2vQ0KPKEhPZn9NhZGi3i3HQyikaYHKVtaz+7KNuy1nYhKQmlez00lcqnGezLnzuR/tM50QYXMG2omdlVXQpfg73yTUh1+6PzBxBST48fKOCsu+TZ/b9QKcEDmAGh9G4SkEUGwnMXK0tYrR701dkm10cS1wTdqERcM6x7mXT4hUlT2FxuEJwen86fDWJ4sZPkki4XartY+FBZofLl7dYokq5J53rxm/I6UXrmieS6D0jJJJWi1stcmddBFx+3a+CLRlr3sRAF5UqOps6XtiJWfRmUQOM0s3VX0rM=
  email:
    recipients:
      secure: JdlKo+iizqpnCdwGGZRcuOvxRngLVhs3ehqZEXjav9i5eEetMo1EpXyOLmga2CyytLfGBKlnCHyySDph6/Q5xcoI1B/YyE6aP75feGmStTj1wyP3xgkGG0zLuqePM8r8FBbSO/x87HGvxzdaS0Wy4AflmRDWte+iCCoFXRz+ceUOB7Xh+wjxcfwU7O3qbjbxKFIxeptPGG/askEtVqR3pLVoyfa9czUV0hrEsO/gR26qKwIYWjT/rDQ67dNXEMouBOAUArU0qmErUl/51t7M/bkIGWrgAFZJP0RCeU7bNMGLY82JtsUqHDdTEOTGWcaEWtpgRd/ljZ21vm/J2gIcZL88pRT5/Usuqh+hlXPKJQ13W4OvME7eB0Xk+W/M/0jCemY+O6uwYCuowRrh9Wr3oup6SabMCBXSiXwlHFUy0FEXzSmupKNnlWd9rH6CfBXhBFXA9nQSEZmc2A4iG6Ih9CJkoY2W8kMMuyb+PKReR80qIgrK4qYwj5zt3ZviPsCwX1ZrimaNTodTk7DumGg9aHGP5fmORrrgwtyeBcGuqKFgznNMyK2PwnuLFkfquod563PY7EJ+o8M6m5mBJm/Kt22o8f9V9QsZSM+ytOprjXs0Hy4GFAlf9qxdUM+ZBHfF1JzZyTTDYTsHokTxA/fsNjvjFbZh5ASbNxsafVwiFKo=
